# Generated by Django 3.1.7 on 2022-04-07 10:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(verbose_name='M Processing Layer Id (Business Module - M Processing Layer Id)')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(verbose_name='M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)')),
                ('processing_layer_id', models.PositiveIntegerField(verbose_name='Processing Layer Id (Business Module - Processing Layer Id)')),
                ('setting_key', models.CharField(max_length=64, null=True, verbose_name='Setting Key')),
                ('setting_value', models.JSONField(null=True, verbose_name='Setting Value')),
                ('setting_description', models.TextField(null=True, verbose_name='Setting Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'module_settings',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(verbose_name='M Processing Layer Id (Business Module - M Processing Layer Id)')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(verbose_name='M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)')),
                ('processing_layer_id', models.PositiveIntegerField(verbose_name='Processing Layer Id (Business Module - Processing Layer Id)')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('report_config', models.JSONField(null=True, verbose_name='Report Config')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='Business Module - User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='TargetFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(verbose_name='M Processing Layer Id (Business Module - M Processing Layer Id)')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(verbose_name='M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)')),
                ('processing_layer_id', models.PositiveIntegerField(verbose_name='Processing Layer Id (Business Module - Processing Layer Id)')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('files_config', models.JSONField(null=True, verbose_name='Files Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='Business Module - User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'target_files',
            },
        ),
        migrations.CreateModel(
            name='TargetFileDefinitions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(verbose_name='M Processing Layer Id (Business Module - M Processing Layer Id)')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(verbose_name='M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)')),
                ('processing_layer_id', models.PositiveIntegerField(verbose_name='Processing Layer Id (Business Module - Processing Layer Id)')),
                ('field_name', models.CharField(max_length=128, null=True, verbose_name='Field Name')),
                ('field_sequence', models.PositiveIntegerField(null=True, verbose_name='Field Sequence')),
                ('files_config', models.JSONField(null=True, verbose_name='Files Config')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='Business Module - User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('target_files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.targetfiles', verbose_name='Target Files Id (Auto Generated)')),
            ],
            options={
                'db_table': 'target_file_definitions',
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(verbose_name='M Processing Layer Id (Business Module - M Processing Layer Id)')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(verbose_name='M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)')),
                ('processing_layer_id', models.PositiveIntegerField(verbose_name='Processing Layer Id (Business Module - Processing Layer Id)')),
                ('source_code', models.CharField(max_length=64, unique=True, verbose_name='Source Code')),
                ('source_name', models.CharField(max_length=64, unique=True, verbose_name='Source Name')),
                ('source_config', models.JSONField(verbose_name='Source Configurations')),
                ('source_input_location', models.CharField(max_length=512, null=True, verbose_name='Source Input Location')),
                ('source_archive_location', models.CharField(max_length=512, null=True, verbose_name='Source Archive Location')),
                ('source_error_location', models.CharField(max_length=512, null=True, verbose_name='Source Error Location')),
                ('source_import_location', models.CharField(max_length=512, null=True, verbose_name='Source Import Location')),
                ('source_import_seq', models.PositiveIntegerField(null=True, verbose_name='Source Import Sequence')),
                ('source_field_number', models.PositiveIntegerField(null=True, verbose_name='Source Field Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='process.sources')),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.CreateModel(
            name='SourceDefinitions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_processing_layer_id', models.PositiveIntegerField(verbose_name='M Processing Layer Id (Business Module - M Processing Layer Id)')),
                ('m_processing_sub_layer_id', models.PositiveIntegerField(verbose_name='M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)')),
                ('processing_layer_id', models.PositiveIntegerField(verbose_name='Processing Layer Id (Business Module - Processing Layer Id)')),
                ('attribute_name', models.CharField(max_length=128, null=True, verbose_name='Attribute Name')),
                ('attribute_position', models.PositiveIntegerField(null=True, verbose_name='Attribute Position')),
                ('attribute_data_type', models.CharField(max_length=32, null=True, verbose_name='Attribute Data Type')),
                ('attribute_date_format', models.CharField(max_length=32, null=True, verbose_name='Attribute Date Format')),
                ('attribute_pattern', models.CharField(max_length=128, null=True, verbose_name='Attribute Pattern')),
                ('attribute_enums', models.JSONField(null=True, verbose_name='Attribute Enums')),
                ('attribute_min_length', models.CharField(max_length=5, null=True, verbose_name='Attribute Minimum Length')),
                ('attribute_max_length', models.CharField(max_length=5, null=True, verbose_name='Attribute Maximum Length')),
                ('attribute_formula', models.CharField(max_length=128, null=True, verbose_name='Attribute Formula')),
                ('attribute_reference_field', models.CharField(max_length=64, null=True, verbose_name='Attribute Reference Field')),
                ('is_validate', models.BooleanField(default=False, verbose_name='To be Validated or not')),
                ('is_required', models.BooleanField(default=True, verbose_name='Required ?')),
                ('is_unique', models.BooleanField(default=False, verbose_name='Unique ?')),
                ('is_editable', models.BooleanField(default=False, verbose_name='Editable ?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='Business Module - User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('sources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.sources', verbose_name='MasterSources Id (Auto Generated)')),
            ],
            options={
                'db_table': 'source_definitions',
            },
        ),
    ]
