# Generated by Django 3.1.7 on 2022-04-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20220407_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='source_name',
            field=models.CharField(max_length=64, verbose_name='Source Name'),
        ),
    ]
