# Generated by Django 3.1.7 on 2022-05-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20220408_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='source_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Source Name'),
        ),
    ]
