# Generated by Django 3.1.7 on 2022-05-08 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_auto_20220505_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('module_id', models.PositiveIntegerField(verbose_name='Module Id (Business Module - Module Id)')),
                ('source_name', models.CharField(max_length=64, verbose_name='Source Name')),
                ('source_type', models.CharField(max_length=64, null=True, verbose_name='Source Type')),
                ('extraction_type', models.CharField(max_length=64, null=True, verbose_name='Extraction Type')),
                ('file_name', models.CharField(max_length=128, null=True, verbose_name='File Name')),
                ('file_size_bytes', models.PositiveIntegerField(null=True, verbose_name='File Size Bytes')),
                ('status', models.CharField(max_length=32, null=True, verbose_name='Status')),
                ('comments', models.TextField(null=True, verbose_name='Comments')),
                ('file_row_count', models.PositiveIntegerField(null=True, verbose_name='File Row Count')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Processed ?')),
                ('file_path', models.CharField(max_length=512, null=True, verbose_name='File Path')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date')),
                ('m_sources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.sources', verbose_name='Sources Id (Auto Generated)')),
            ],
            options={
                'db_table': 'file_uploads',
            },
        ),
    ]
