# Generated by Django 3.1.7 on 2022-05-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_fileuploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploads',
            name='created_date',
            field=models.CharField(max_length=32, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='fileuploads',
            name='modified_date',
            field=models.CharField(max_length=32, null=True, verbose_name='Modified Date'),
        ),
    ]
