# Generated by Django 3.1.7 on 2022-05-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_auto_20220508_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploads',
            name='module_id',
        ),
        migrations.AddField(
            model_name='fileuploads',
            name='m_processing_layer_id',
            field=models.PositiveIntegerField(default=1, verbose_name='M Processing Layer Id (Business Module - M Processing Layer Id)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileuploads',
            name='m_processing_sub_layer_id',
            field=models.PositiveIntegerField(default=1, verbose_name='M Processing Sub Layer Id (Business Module - M Processing Sub Layer Id)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileuploads',
            name='processing_layer_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Processing Layer Id (Business Module - Processing Layer Id)'),
            preserve_default=False,
        ),
    ]
