# Generated by Django 3.1.7 on 2022-06-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_auto_20220508_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulesettings',
            name='created_date',
            field=models.CharField(max_length=32, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='modulesettings',
            name='modified_date',
            field=models.CharField(max_length=32, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='created_by',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='User Id'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='created_date',
            field=models.CharField(max_length=32, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='modified_date',
            field=models.CharField(max_length=32, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='sourcedefinitions',
            name='created_by',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='User Id'),
        ),
        migrations.AlterField(
            model_name='sourcedefinitions',
            name='created_date',
            field=models.CharField(max_length=32, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='sourcedefinitions',
            name='modified_date',
            field=models.CharField(max_length=32, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='created_date',
            field=models.CharField(max_length=32, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='modified_date',
            field=models.CharField(max_length=32, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='targetfiledefinitions',
            name='created_by',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='User Id'),
        ),
        migrations.AlterField(
            model_name='targetfiledefinitions',
            name='created_date',
            field=models.CharField(max_length=32, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='targetfiledefinitions',
            name='modified_date',
            field=models.CharField(max_length=32, null=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='targetfiles',
            name='created_by',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='User Id'),
        ),
        migrations.AlterField(
            model_name='targetfiles',
            name='created_date',
            field=models.CharField(max_length=32, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='targetfiles',
            name='modified_date',
            field=models.CharField(max_length=32, null=True, verbose_name='Modified Date'),
        ),
    ]
