# Generated by Django 3.1.7 on 2022-06-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_auto_20220609_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='key_words',
            field=models.JSONField(null=True, verbose_name='Key Words'),
        ),
    ]
