# Generated by Django 3.1.7 on 2022-06-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_sources_key_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetfiles',
            name='name',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='Name'),
        ),
    ]
