# Generated by Django 3.1.7 on 2022-07-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_auto_20220625_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploads',
            name='gst_month',
            field=models.CharField(max_length=32, null=True, verbose_name='GST Month'),
        ),
    ]
