# Generated by Django 3.1.7 on 2022-07-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0011_fileuploads_gst_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetfiledefinitions',
            name='storage_reference_column',
            field=models.CharField(max_length=32, null=True, verbose_name='Storage Reference Column'),
        ),
    ]
