# Generated by Django 3.1.7 on 2022-07-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0012_targetfiledefinitions_storage_reference_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetfiledefinitions',
            name='field_type',
            field=models.CharField(max_length=32, null=True, verbose_name='Field Type'),
        ),
    ]
