# Generated by Django 3.1.7 on 2021-12-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastersources',
            old_name='sources_id',
            new_name='sources',
        ),
    ]
