# Generated by Django 3.1.7 on 2021-12-18 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_auto_20211218_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldExtraction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_aggregator_id', models.PositiveIntegerField(verbose_name='Aggregator Id (MasterAggregators)')),
                ('m_sources_id', models.PositiveIntegerField(verbose_name='Sources Id (MasterSources)')),
                ('m_source_definitions_id', models.PositiveIntegerField(verbose_name='Source Definitions Id (MasterSourceDefinitions)')),
                ('pattern_type', models.CharField(max_length=255, verbose_name='Pattern Type')),
                ('pattern_input', models.CharField(max_length=255, verbose_name='Pattern Input')),
                ('transaction_placed', models.CharField(max_length=255, verbose_name='Transaction Placed')),
                ('transaction_reference', models.CharField(max_length=255, verbose_name='Transaction Reference')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'field_extraction',
            },
        ),
        migrations.CreateModel(
            name='MasterTransformations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenants_id', models.PositiveIntegerField(verbose_name='Tenants Id (Business Module - Tenant Id)')),
                ('groups_id', models.PositiveIntegerField(verbose_name='Groups Id (Business Module - Groups Id)')),
                ('entities_id', models.PositiveIntegerField(verbose_name='Entities Id (Business Module - Entities Id)')),
                ('m_aggregator_transformations_id', models.PositiveIntegerField(verbose_name='M Aggregators Transformations Id (MasterAggregatorTransformations)')),
                ('transformation_name', models.CharField(max_length=255, verbose_name='Transformation Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_by', models.PositiveSmallIntegerField(null=True, verbose_name='User Id')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'db_table': 'm_transformations',
            },
        ),
        migrations.AddField(
            model_name='fieldextraction',
            name='m_transformations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.mastertransformations', verbose_name='M Transformations Id (MasterTransformations)'),
        ),
    ]
