# Generated by Django 3.1.7 on 2021-12-20 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_auto_20211219_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastertransformations',
            name='m_aggregator_transformations_id',
        ),
        migrations.AddField(
            model_name='mastertransformations',
            name='m_transformation_types_id',
            field=models.PositiveIntegerField(default=1, verbose_name='M Transformation Types Id (MasterTransformationTypes)'),
            preserve_default=False,
        ),
    ]
